name: code-quality-workflow-name
run-name: code quality workflow run name
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  pre-commit-job-identifier:
    name: pre-commit job name
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: checkout commit step
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
      - name: set up python step
        uses: actions/setup-python@v6
        with:
          python-version: ">=3.13 <3.14"
          check-latest: true
          architecture: x64
          cache: pip
          cache-dependency-path: |
            pyproject.toml
            uv.lock
      - name: install pre-commit step
        run: python3 -m pip install pre-commit
      - name: install pre-commit hooks step
        run: python3 -m pre_commit install-hooks
      - name: run pre-commit hooks step
        env:
          SKIP: no-commit-to-branch
        run: python3 -m pre_commit run --all-files --show-diff-on-failure
