name: docs-deploy-workflow-name
run-name: docs deploy workflow run name
on:
  push:
    branches:
      - main
    paths:
      - docs/**
      - mkdocs.yml
      - .github/workflows/docs.yml
permissions:
  contents: write
defaults:
  run:
    shell: bash
jobs:
  mkdocs-deploy-job-identifier:
    name: mkdocs deploy job name
    runs-on: ubuntu-latest
    steps:
      - name: checkout commit step
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
      - name: git credentials configuration step
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: set up python step
        uses: actions/setup-python@v6
        with:
          python-version: ">=3.13 <3.14"
          check-latest: true
          architecture: x64
          cache: pip
          cache-dependency-path: |
            pyproject.toml
            uv.lock
      - name: install docs dependencies step
        run: python3 -m pip install --group docs
      - name: deploy mkdocs site step
        run: mkdocs gh-deploy --clean --force --strict
